sudo: required
dist: trusty
language: python
python:
  - "3.5"
jobs:
  include:
    - stage: first
      name: "Trigger rebuild of kasper installer"
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        sh .travis_scripts/trigger-travis.sh --branch development fossasia kasper_installer $TRAVIS_ACCESS_TOKEN


#
# disabled since it does not work and no tests are available at the moment
#    - stage: first # runs in parallel with the previous job
#      script: |
#        sudo apt-get update --fix-missing
#        # We are going to install realpath, which comes as a separate package in Ubuntu Trusty
#        sudo apt-get install realpath
#        chmod +x .travis_scripts/install.sh
#        ./.travis_scripts/install.sh
#        pip3 install -U pytest
#        pip3 install -U pep8
#    - stage: test # runs after the first stop has finished
#      script: |
#        pep8 kasper_linux --ignore E501 --exclude=kasper_linux/hotword_engine/snowboy_detector.py
#        python3 -m pytest tests/
