#!/bin/sh
# Start/Stop the kasper.AI main program

# this wrapper is installed as follows:
# user mode
#   .../kasper.AI/bin/
#   .../kasper.AI/pythonmods/
# system mode
#   prefix/bin/
#   prefix/lib/kasper.AI/pythonmods

DIR="$(dirname "$(readlink -f "$0")")"
PMA="$(readlink -m "$DIR/../pythonmods")"
PMB="$(readlink -m "$DIR/../lib/kasper.AI/pythonmods")"
if [ -d "$PMA" ] && [ -r "$PMA/kasper_linux" ] ; then
    LOGDIR="$(readlink -m "$DIR/../logs")"
    PYTHONPATH="$PMA":$PYTHONPATH
    export PYTHONPATH
elif [ -d "$PMB" ] && [ -r "$PMB/kasper_linux" ] ; then
    LOGDIR=$HOME/.kasper.ai/logs
    PYTHONPATH="$PMB":$PYTHONPATH
    export PYTHONPATH
else
    echo "Cannot find kasper.AI pythonmods, trying without it" >&2
fi

CMD="python3 -m kasper_linux -v --short-log"

do_start() {
    mkdir -p "$LOGDIR"
    python3 -m kasper_linux -v --short-log > "$LOGDIR/kasper-linux.log" 2>&1 &
    sleep 3
    echo "kasper-linux has started, logging to $LOGDIR/kasper-linux.log"
}

do_stop() {
    pkill -f kasper_linux
}

case "$1" in
    start)
        do_start ;;
    stop)  
        do_stop  ;;
    restart)
        do_stop ; sleep 1 ; do_start ;;
    *) 
        echo "Usage: kasper-linux {start|stop|restart}" >&2
        exit 1
        ;;
esac


